/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yerel Kullanıcı
 */

import java.sql.*;
import java.awt.event.*;
import java.awt.*;

public class Quests_jFrame extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs= null;
PreparedStatement pst = null;
    /**
     * Creates new form Quests_jFrame
     */
    public Quests_jFrame() {
        initComponents();
        conn = javaConnect.ConnecrDb();
        setResizable(false);
        setBounds(260, 100, 1322, 800);
        
        quest1_complete_button.setEnabled(false);
        quest2_complete_button.setEnabled(false);
        quest3_complete_button.setEnabled(false);
        quest4_complete_button.setEnabled(false);
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        SUBJECT = new javax.swing.JLabel();
        SUBJECT1 = new javax.swing.JLabel();
        SUBJECT2 = new javax.swing.JLabel();
        SUBJECT3 = new javax.swing.JLabel();
        Quest1_text = new javax.swing.JLabel();
        Quest2_text = new javax.swing.JLabel();
        Quest3_text = new javax.swing.JLabel();
        Quest4_text = new javax.swing.JLabel();
        quest2_complete_button = new javax.swing.JButton();
        quest3_complete_button = new javax.swing.JButton();
        quest4_complete_button = new javax.swing.JButton();
        quest1_complete_button = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUESTS");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 10, 480, 80);

        SUBJECT.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        SUBJECT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUBJECT.setText("QUESTS 2");
        SUBJECT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(SUBJECT);
        SUBJECT.setBounds(380, 170, 240, 60);

        SUBJECT1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        SUBJECT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUBJECT1.setText("QUESTS 3");
        SUBJECT1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(SUBJECT1);
        SUBJECT1.setBounds(690, 170, 240, 60);

        SUBJECT2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        SUBJECT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUBJECT2.setText("QUESTS 4");
        SUBJECT2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(SUBJECT2);
        SUBJECT2.setBounds(1010, 170, 240, 60);

        SUBJECT3.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        SUBJECT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SUBJECT3.setText("QUESTS 1");
        SUBJECT3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(SUBJECT3);
        SUBJECT3.setBounds(60, 170, 240, 60);

        Quest1_text.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        Quest1_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quest1_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(Quest1_text);
        Quest1_text.setBounds(40, 250, 290, 60);

        Quest2_text.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        Quest2_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quest2_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(Quest2_text);
        Quest2_text.setBounds(360, 250, 290, 60);

        Quest3_text.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        Quest3_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quest3_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(Quest3_text);
        Quest3_text.setBounds(670, 250, 290, 60);

        Quest4_text.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        Quest4_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quest4_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        getContentPane().add(Quest4_text);
        Quest4_text.setBounds(990, 250, 290, 60);

        quest2_complete_button.setBackground(new java.awt.Color(51, 51, 51));
        quest2_complete_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest2_complete_button.setText("COMPLETE QUEST 2");
        quest2_complete_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quest2_complete_button.setContentAreaFilled(false);
        getContentPane().add(quest2_complete_button);
        quest2_complete_button.setBounds(420, 330, 180, 70);

        quest3_complete_button.setBackground(new java.awt.Color(51, 51, 51));
        quest3_complete_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest3_complete_button.setText("COMPLETE QUEST 3");
        quest3_complete_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quest3_complete_button.setContentAreaFilled(false);
        getContentPane().add(quest3_complete_button);
        quest3_complete_button.setBounds(730, 330, 180, 70);

        quest4_complete_button.setBackground(new java.awt.Color(51, 51, 51));
        quest4_complete_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest4_complete_button.setText("COMPLETE QUEST 4");
        quest4_complete_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quest4_complete_button.setContentAreaFilled(false);
        getContentPane().add(quest4_complete_button);
        quest4_complete_button.setBounds(1060, 330, 180, 70);

        quest1_complete_button.setBackground(new java.awt.Color(51, 51, 51));
        quest1_complete_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest1_complete_button.setText("COMPLETE QUEST 1");
        quest1_complete_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quest1_complete_button.setContentAreaFilled(false);
        getContentPane().add(quest1_complete_button);
        quest1_complete_button.setBounds(100, 330, 180, 70);

        Back_button.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        Back_button.setForeground(new java.awt.Color(204, 204, 204));
        Back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_icon_axe.png"))); // NOI18N
        Back_button.setText("BACK");
        Back_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_button.setContentAreaFilled(false);
        Back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Back_buttonMouseExited(evt);
            }
        });
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_button);
        Back_button.setBounds(1081, 480, 160, 71);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quests.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1322, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_buttonMouseEntered
        Back_button.setFont(new java.awt.Font("Stencil", 0, 18));
    }//GEN-LAST:event_Back_buttonMouseEntered

    private void Back_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_buttonMouseExited
        Back_button.setFont(new java.awt.Font("Stencil", 0, 14));
    }//GEN-LAST:event_Back_buttonMouseExited

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        NewGame_jFrame.soundOn();
            
        MainMenu_jFrame.newGame.setVisible(true);  

        close();
    }//GEN-LAST:event_Back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quests_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quests_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quests_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quests_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quests_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    public static javax.swing.JLabel Quest1_text;
    public static javax.swing.JLabel Quest2_text;
    public static javax.swing.JLabel Quest3_text;
    public static javax.swing.JLabel Quest4_text;
    private javax.swing.JLabel SUBJECT;
    private javax.swing.JLabel SUBJECT1;
    private javax.swing.JLabel SUBJECT2;
    private javax.swing.JLabel SUBJECT3;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JButton quest1_complete_button;
    public static javax.swing.JButton quest2_complete_button;
    public static javax.swing.JButton quest3_complete_button;
    public static javax.swing.JButton quest4_complete_button;
    // End of variables declaration//GEN-END:variables
}
